# https://www.youtube.com/watch?v=xUJoeOC1t0M
name: Lint
on: pull_request
jobs:
  build:
    name: Lint App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run eslint:github-action

      - name: Annotated Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        if: always()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
