# https://www.youtube.com/watch?v=xUJoeOC1t0M
name: Lint
on: pull_request
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  build:
    name: Lint App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run eslint:github-action

      - name: Annotated Code Linting Results
        uses: ataylorme/eslint-annotate-action@4.0.0
        if: always()
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
